### ISSUE TITLE
The install sections doesn't mention RedCloth

### ISSUE THREAD

**Issue by inputsh** [steinvc/holo-alfa#2]
In the installation instructions (located in the `README.md` file) I see no mention of RedCloth gem. Without it, I was not able to run `jekyll serve` successfully (even though this works with other Jekyll themes).

So, maybe you should consider pitching that into the `README.md` file?

Here's the terminal output I got:

```
/home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/resolver.rb:202:in `rescue in start': Bundler could not find compatible versions for gem "RedCloth": (Bundler::VersionConflict)
  In snapshot (Gemfile.lock):
    RedCloth (= 4.2.9)

  In Gemfile:
    github-pages (>= 0) ruby depends on
      RedCloth (= 4.2.9) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/resolver.rb:198:in `start'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/resolver.rb:182:in `resolve'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/definition.rb:200:in `resolve'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in `specs'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in `requested_specs'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in `setup'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/jekyll-2.5.3/lib/jekyll/plugin_manager.rb:37:in `require_from_bundler'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/gems/jekyll-2.5.3/bin/jekyll:16:in `<top (required)>'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `load'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/bin/jekyll:23:in `<main>'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
    from /home/r3bl/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

`bundle update` did fix the error to me, but others might be confused and miss that.

**Comment by stijnvc** [comment]
Thanks for the suggestion. The terminal output already suggests a solution that works. I'm not going to mention a RedCloth compatibility issue in `README.md`.
